backend:
  name: github
  repo: bluerosegarden/dandyliondreamers-site
  branch: main

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

collections:
- name: "pages"
  label: "Pages"
  files:
    - label: "Home Page"
      name: "home"
      file: "src/lib/cms/pages/home.json"
      format: json
      fields:
        - {label: Page Title, name: title, widget: string}
        - {label: Embed Blurb, name: blurb, widget: string}
        - {label: "Main Image", name: "mainImg", widget: "image", choose_url: true}
        - {label: "Embed Image", name: "embedImg", widget: "image", choose_url: true}
        - {label: Body, name: body, widget: markdown}
    - label: "About Page"
      name: "about"
      file: "src/lib/cms/pages/about.json"
      format: json
      fields:
        - {label: Page Title, name: title, widget: string}
        - {label: "Main Image", name: "mainImg", widget: "image", choose_url: true, required: false}
        - {label: Body, name: body, widget: markdown}
    - label: "Commissions Page"
      name: "commissions"
      file: "src/lib/cms/pages/commissions.json"
      format: json
      fields:
        - {label: Page Title, name: title, widget: string}
        - {label: "Main Image", name: "mainImg", widget: "image", choose_url: true, required: false}
        - {label: Body, name: body, widget: markdown}
    - label: "Portfolio"
      name: "portfolio"
      file: "src/lib/cms/pages/portfolio.json"
      format: json
      fields:
        - {label: Page Title, name: title, widget: string}
        - {label: Body, name: body, widget: markdown}
        - label: Portfolio Sets
          name: portSets
          widget: list
          fields:
          - {label: "Set Title", name: "title", widget: "string", required: false}
          - {label: "Set Description", name: "desc", widget: "string", required: false}
          - {label: "Link", name: "link", widget: "string", required: false}
          - {label: "Background Color", name: "bg-color", widget: "color", default: "#ffb188", required: false}
          - label: Images 
            name: images 
            widget: list 
            fields:
            - {label: "Image", name: "img", widget: "image", choose_url: true}
            - {label: "Image Title", name: "title", widget: "string", required: false}
            - {label: "Image Source (link)", name: "link", widget: "string", required: false}
            - {label: "Image Description", name: "desc", widget: "string", required: false}
              
    - label: "Rayqueza"
      name: "rayqueza"
      file: "src/lib/cms/pages/rayqueza.json"
      format: json
      fields:
        - {label: Page Title, name: title, widget: string}
        - {label: Body, name: body, widget: markdown}
        - label: Rayqueza Sets
          name: raySets
          widget: list
          fields:
          - {label: "Rayqueza Title", name: "title", widget: "string", required: false}
          - {label: "Rayqueza Description", name: "desc", widget: "markdown", required: false}
          - {label: "Link", name: "link", widget: "string", required: false}
          - {label: "Image", name: "img", widget: "image", choose_url: true}
              
- name: "settings"
  label: "Settings"
  files:
    - label: "Main Settings"
      name: "mainSettings"
      file: "src/lib/cms/pages/main-settings.json"
      format: json
      fields:
        - {label: Email, name: email, widget: string}
        - {label: Embed Blurb, name: blurb, widget: string}
        - {label: "Embed Image", name: "embedImg", widget: "image", choose_url: true}
        - {label: "Site Title", name: title, widget: string}
        - {label: "Site URL", name: url, widget: string}
        - label: Links
          name: links
          widget: list
          required: false
          fields:
            - {label: Link Name, name: name, widget: string}
            - {label: Link, name: link, widget: string}